### ISSUE TITLE
Instance of 'InstantiationException' on Landing Screen

### ISSUE THREAD

**Issue by Dehmee** [heremaps/here-sdk-ref-app-flutter#105]
I keep getting an "Instance of 'InstantiationException'" exception whenever I try to run the downloaded project. I have added the HERE SDK to the plugins folder (version: 4.15.2) but it fails every time I run it. The exception comes from assigning the Position Engine userConsentState to the _consentState variable on the landing screen. Here is the full error message:

`======== Exception caught by widgets library =======================================================
The following InstantiationException was thrown building Consumer2<AppPreferences, CustomMapStyleSettings>(dirty, dependencies: [_InheritedProviderScope<AppPreferences?>, _InheritedProviderScope<CustomMapStyleSettings?>, _InheritedTheme, _LocalizationsScope-[GlobalKey#1046e]]):
Instance of 'InstantiationException'

The relevant error-causing widget was: 
  Consumer2<AppPreferences, CustomMapStyleSettings> Consumer2:file:///C:/src/here/here_reference_app/here-sdk-ref-app-flutter-master-v.4.15.2/lib/landing_screen.dart:109:12
When the exception was thrown, this was the stack: 
#0      ConsentInternal$Impl.fromSharedSdkNativeEngine (package:here_sdk/src/sdk/consent/consent_internal.dart:191:11)
#1      ConsentInternal.fromSharedSdkNativeEngine (package:here_sdk/src/sdk/consent/consent_internal.dart:46:68)
#2      new ConsentEngine (package:here_sdk/src/sdk/consent/consent_engine.dart:25:63)
#3      PositioningEngine._consentEngine (package:RefApp/positioning/positioning_engine.dart:34:69)
#4      PositioningEngine._consentEngine (package:RefApp/positioning/positioning_engine.dart)
#5      PositioningEngine.userConsentState (package:RefApp/positioning/positioning_engine.dart:51:45)
#6      _LandingScreenState._buildUserConsentItems (package:RefApp/landing_screen.dart:195:39)
#7      _LandingScreenState._buildDrawer (package:RefApp/landing_screen.dart:367:16)
#8      _LandingScreenState.build.<anonymous closure> (package:RefApp/landing_screen.dart:122:17)
#9      Consumer2.buildWithChild (package:provider/src/consumer.dart:206:19)
#10     SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
#11     StatelessElement.build (package:flutter/src/widgets/framework.dart:5367:49)
#12     SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279:5)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
#17     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (228 frames)
#245    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#246    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#247    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (447 frames)
#694    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#701    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#708    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#715    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#722    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#729    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#736    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#743    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#750    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#757    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#764    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#771    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#778    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#785    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#792    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#799    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#806    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#813    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#820    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (35 frames)
#855    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#856    Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#857    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#858    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#859    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
#860    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719:19)
#861    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
#862    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
#863    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981:7)
#867    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================`

**Comment by stefan-troyke** [comment]
Hi, you need to stick to HERE SDK 4.15.0.0. The project integrates only the major versions at the moment, see the readme file for the correct version.

**Comment by stefan-troyke** [comment]
Hi, sorry for the inconvenience but it seems our portal only allows to download the current vertsion at the moment. I opened a ticket for this. Please get back to the account manager or the technical cosumer support. They will help you on this matter.
