### ISSUE TITLE
Not able to customize HERE MAP cluster marker and Single Marker UI

### ISSUE THREAD

**Issue by gh-yatinIshwarlalDeokar** [heremaps/here-sdk-ref-app-flutter#107]
Cluster Marker image and text style can be change but cluster count text **alignment** would be always on center and not able to modify  or add any other component along with it. and marker is not getting resized with map zoom in and zoom out. for flutter.

Also there is not direct option to pass **custom widget** as marker. its only accepting **.png or svg tiny.** 

I want custom widget as marker for both cluster and single marker as shown in image along with **dotted polygon border**. is there any way to achieve that.
using **Here Map SDK Version 4.15.5.0** 

**Following code for Marker(Didn't find way to change image once set):**
`MapImage.withPixelDataAndImageFormat(Uint8List, ImageFormat.png)`

**Currently Able to show cluster counter with following code:**
`MapMarkerClusterCounterStyle counterStyle = MapMarkerClusterCounterStyle();
    counterStyle.textColor = Colors.black;
    counterStyle.fontSize = 80;
MapMarkerCluster mapMarkerCluster =
    MapMarkerCluster.WithCounter(MapMarkerClusterImageStyle(_singleMarkerImage), counterStyle));`

**Cluster Marker:** 
![image](https://github.com/heremaps/here-sdk-ref-app-flutter/assets/144206273/3fd4699a-6fd6-414c-a687-6c425f2c2b94)

**Single Marker:**
![image](https://github.com/heremaps/here-sdk-ref-app-flutter/assets/144206273/1e7c6f1a-7db2-4372-9058-e86773bb56cf)

**Comment by stefan-troyke** [comment]
This is a feature request for the HERE SDK but not the reference application. I will forward this to the product management.

**Comment by gh-venkateshamurthy** [comment]
@stefan-troyke can you please take this as priority

**Comment by gh-venkateshamurthy** [comment]
@stefan-troyke any updates ?

**Comment by stefan-troyke** [comment]
Hi,

the matter was discussed with the product owner and the request will be added to the backlog. Nevertheless the desired design can also be achieved with MapMarkerClusterCounterStyle.textAnchor.

**Comment by gh-yatinIshwarlalDeokar** [comment]
Hi @stefan-troyke ,
Is there any cluster builder or addClusterLayer option available, or any temporary solution where I can add custom text to cluster for now. meanwhile team is adding this feature in SDK itself .
