### ISSUE TITLE
Failed to lookup symbol 'here_sdk_sdk_core_GeoCoordinates_make__Double_Double'

### ISSUE THREAD

**Issue by novas1r1** [heremaps/here-sdk-ref-app-flutter#109]
Hey there,
Thank you for the package! I'm working with the here_sdk in my flutter app and everything is working fine. I wanted to write some tests to cover some functionality but as soon as I want to use classes from the here_sdk - in my case `GeoCoordinates` - I can't run my test and the following error appears:

```
Invalid argument(s): Failed to resolve an FFI function. Perhaps `LibraryContext.init()` was not called.
Failed to lookup symbol 'here_sdk_sdk_core_GeoCoordinates_make__Double_Double': dlsym(RTLD_DEFAULT, here_sdk_sdk_core_GeoCoordinates_make__Double_Double): symbol not found
```

I tried initializing the SDK using `SdkContext.init();` in my setupAll-test-method, but it didn't help.

Flutter version: 3.7.12
Dart: 2.19.6
here_sdk: 4.15.5

Any hints are highly appreciated!
Thanks in advance

**Comment by stefan-troyke** [comment]
Hi,

what is the test framework you are using? Do you want to test SDK code directly? If not, did you thought about mocking the SDK classes?

**Comment by HERE-SDK-Support-Team** [comment]
@novas1r1 You may want to check this [unit_test](https://github.com/heremaps/here-sdk-examples/blob/master/examples/latest/navigate/flutter/unit_testing_app/test/main_test.dart) example app.

It shows how to use core classes from the HERE SDK with Flutter unit tests using Mockito. More about this in this [user guide](https://www.here.com/docs/bundle/sdk-for-flutter-navigate-developer-guide/page/topics/key-concepts.html#unit-tests).

Hope this helps already to solve your issues. Closing for now. Please leave a reply if you have more questions. Thanks!

**Comment by novas1r1** [comment]
Hey @HERE-SDK-Support-Team!
Thank you very much for your fast response, this helps :)
