### ISSUE TITLE
White screen issue

### ISSUE THREAD

**Issue by Riyazali613618** [heremaps/here-sdk-ref-app-flutter#140]
I just downloaded the hello_map_app example and replaces the credentials keys. After successfully compiling and running the app it's just showing a blank screen. But when press recent tab button in android phone and click on the app it shows map on the screen. This happened even if I create a new app and new credentials or using the official provided github example.

**Comment by stefan-troyke** [comment]
Hi,

I think you posted this to the wrong application. This is the HERE SDK reference application for Flutter. I guess you refer to our example repository?

https://github.com/heremaps/here-sdk-examples

Please confirm.

**Comment by HERE-SDK-Support-Team** [comment]
@Riyazali613618 Could it be that you are using Flutter 3.16 or higher and Android 14? If so, this could be a [known Flutter issue](https://github.com/flutter/engine/pull/50792https://github.com/flutter/engine/pull/50792). Either way, if the problem persists, please file an issue [here](https://github.com/heremaps/here-sdk-examples/issues/new).
