### ISSUE TITLE
 Failed to async download a tile, running on Android 7 and 8

### ISSUE THREAD

**Issue by scharlton** [heremaps/here-sdk-ref-app-flutter#142]
Hi, 

I have followed the instructions to run this app on our devices. On Android 10 and above everything is fine. But on the devices we have tested that have Android 7 and 8 all encounter the issue of a blank map. 

I have tried with other samples such as hello_map_app and still encounter the same problem. I tried to change the rendering mode to texture with no luck but looking at the logs _(a sample below)_ its failing to download the tiles. Which led me to think credentials was the problem but as its working on newer devices I'm not sure its a credential issue. 

Tried to test on WIFI and cellular. The devices all seem to meet the minimum specification required.

**Versions used:** 
Flutter 3.16.3
Dart SDK version: 3.2.3
gradle:7.4.2

**Device Spec:**

![Capture_22022024_3](https://github.com/heremaps/here-sdk-ref-app-flutter/assets/4697862/77cb8be3-30e5-4884-a7e7-0c950f42302c)
![Capture_22022024_2](https://github.com/heremaps/here-sdk-ref-app-flutter/assets/4697862/e46b83bb-c512-4c6c-8fde-7f61c01364ee)
![Capture_22022024_4](https://github.com/heremaps/here-sdk-ref-app-flutter/assets/4697862/1555ad51-fc69-4f83-ba27-a71856c6a0b4)

**Sample of logs:**
W/DataStoreClient(13903): [WARN ] hsdk-DataStoreClient - Failed to async download a tile, please retry, catalog_handle=all, request=377894441@rendering, error=kRequestCancelled

W/DataStoreClient(13903): [WARN ] hsdk-DataStoreClient - Failed to async download a tile, please retry, catalog_handle=all, request=377894441@rendering, error=kRequestCancelled

W/DataStoreClient(13903): [WARN ] hsdk-DataStoreClient - Failed to async download a tile, please retry, catalog_handle=all, request=377894441@rendering, error=kRequestCancelled

I/RetryNetwork(13903): [INFO ] hsdk-RetryNetwork - Cancelling request parentId=8 realId=7 in the network delegate

I/RetryNetwork(13903): [INFO ] hsdk-RetryNetwork - Finishing request to url=https://direct.data.api.platform.here.com/direct/v1/query/catalogs/hrn:here:data::olp-here:ocm/layers/index/partitions?additionalFields=dataSize%2Ccrc%2Cchecksum&partition=rendering&version=109 parentId=23 realId=22 with status=OK message=OK

I/DataRepository(13903): [INFO ] hsdk-DataRepository - GetBlobData not found in cache, hrn='hrn:here:data::olp-here:ocm', key='56789087654678908765.109'

**Comment by stefan-troyke** [comment]
Hi, we will look into this issue and get back to you

**Comment by scharlton** [comment]
Thankyou, I'm using HERE SDK for Flutter version 4.17.0 and app version 1.8.0. 

I can see that 1.9.0 was released yesterday and can give that a try too.

**Comment by stefan-troyke** [comment]
I checked already and the issue remains... We are working on it... Nevertheless I don't expect a fast resolution since we only integrate only major HERE SDK release in the moment...

**Comment by stefan-troyke** [comment]
Latest update is that this seems to be a pure Flutter issue. Rolling back to Flutter version 3.13.9 or upgrade to Flutter version 3.22.0 fixes the issue. We will release the app version 1.10.0 with Flutter version 3.22.0

**Comment by stefan-troyke** [comment]
The issue has been fixed on master and verified with Android 6. A official release will follow soon.
