### ISSUE TITLE
How to add functionality like 3d map view and compass like in here maps app using flutter sdk

### ISSUE THREAD

**Issue by mohanve7** [heremaps/here-sdk-ref-app-flutter#164]
![Screenshot_20240822_164902](https://github.com/user-attachments/assets/8f1f2021-9bc4-4bce-a889-3a0569572185)

**Comment by Guru-cm-here** [comment]
Hi @mohanve7 
Currently, we do not have a built-in widget for the compass feature. However, this can be achieved by adding an icon on top of the MapView. When pressed, you can update the `camera` for the HereMapController object.

You can use the `mapController.camera.lookAtPointWithGeoOrientationAndMeasure` method.

API Reference: https://www.here.com/docs/bundle/sdk-for-android-explore-api-reference/page/com/here/sdk/mapview/MapCamera.html
