### ISSUE TITLE
consent.dart and location.dart doesn't exist in here_sdk 4.19.5.0

### ISSUE THREAD

**Issue by otoo-peacemaker** [heremaps/here-sdk-ref-app-flutter#165]
main.dart

![Screenshot from 2024-08-31 10-44-15](https://github.com/user-attachments/assets/f6e4980c-ac0e-4e70-a026-a460bcfdac4f)

project structure and pubspec.yaml

![Screenshot from 2024-08-31 10-46-59](https://github.com/user-attachments/assets/395cf4ed-613b-4791-810f-d784d03677da)

**Comment by HERE-SDK-Support-Team** [comment]
Hi @otoo-peacemaker , this looks like a question for the HERE SDK example apps. You can repost your question here: https://github.com/heremaps/here-sdk-examples/issues

However, it looks like you are trying the example app with the plugin from the Explore Edition? Could this be? Please refer to the official documentation: https://github.com/heremaps/here-sdk-examples

Hope this helps. Thanks!
