### ISSUE TITLE
SDK 4 - only one listener for Navigator

### ISSUE THREAD

**Issue by Azbesciak** [heremaps/here-sdk-ref-app-flutter#45]
Excuse me, but the other way is to write to your support team, which seems to be pointless.
Why did you allow only one listener of each type for `Navigator`? I suppose it is the same as `NavigationManager`, which in the previous version could be a singleton, and also could have multiple listeners of each type. Of course, I can have some aggregating listener, for each type, but ...
And what with, for example, map gesture listeners?

I would even notice that in the early android ages they also had one listener with `set`, and sometime later they changed to `add` approach.

**Comment by datasun** [comment]
Hi @Azbesciak , thanks for trying out the Ref App. 

The HERE SDK supports [both approaches](https://developer.here.com/documentation/android-sdk-navigate/4.9.4.0/dev_guide/topics/key-concepts.html#conventions), depending on the feature:

"When multiple listeners can be set, then the method pattern `add_x()` and `remove_x()` is used as naming convention. If only one listener can be set at a time, the `set_x()` pattern is used that can be set to `null` to stop listening."

The actual replacement of the 3.x `NavigationManager` is indeed the `Navigator` _or_ the `VisualNavigator`. It follows the `set_x()` convention as we believe for most use cases this fits better in a TBT context. If you really need to forward multiple events to multiple listeners, then indeed you can do this on app side. If there are strong reasons to add such a feature for convenience, please let us know, then we can eventually consider it for our future planning.

Gesture listeners are explained [here](https://developer.here.com/documentation/android-sdk-navigate/4.9.4.0/dev_guide/topics/gestures.html) and yes, they follow also the single listener approach. In most cases this leads to a better app architecture when there is only one source for an event that can then be individually forwarded for specific purposes.

**Comment by Azbesciak** [comment]
@datasun , one single example - POI selection/feature segregation. there is just one gesture listener, on tap - right?
Now, you click on the map. Do you want to select a traffic incident, a marker, a route, a POI?

You have a speed warning listener, and you want multiple features like custom sound, sending some http requests to the server, notify the user, make the screen red. I do not know.
I already saw your migration guide, as the same as I saw your colleague's comment https://github.com/heremaps/msdkui-ios/issues/210#issuecomment-1022031660, and I would say that there is very little chance to migrate and not to change the whole app logic.

**Comment by datasun** [comment]
Thanks for the feedback, @Azbesciak. We will consider it for our future planning.

If you want to pick several types of map items, then only _one_ tap listener should be needed: With the 4.x SDK you only need a call to `mapView.pickMapFeatures()`. The `MapViewBase.PickMapFeaturesCallback()` delivers then the [possible results](https://developer.here.com/documentation/android-sdk-navigate/4.9.4.0/dev_guide/topics/map-items.html#pick-embedded-pois). Note there is also a `PickMapItemsResult` and `PickMapItemsCallback` to enforce separation. The pattern to use would be `onTap(){ doA, doB, ... }` which makes the code easier to read.

Unfortunately, you are right, the migration from 3.x to 4.x can be a greater effort. This is because the 4.x stack is completely different. Compared to this, the missing support for multiple listeners is probably quite minor as this can be implemented easily on app side. Overall, the 4.x follows a more aligned and cleaner approach in its API design, so we believe - at the end - also the resulting code is easier to read and to maintain. 

In the > 4.9.4 version of the migration guide, you will find a 1:1 comparsion table of the old versus new [example apps](https://github.com/heremaps/here-sdk-examples).

**Comment by Azbesciak** [comment]
![Screenshot_20220129-113106](https://user-images.githubusercontent.com/17334466/151657597-ef159189-be81-4bb1-9279-88c31e0c5bd7.png)
Yes, thanks... I suppose it works on desktop

**Comment by Azbesciak** [comment]
> With 4.10.1.0 Navigate Edition you can specify a feature configuration (see MapDownloader) - this allows to disable certain features you do not need. As a result, less map data is required.

I think that the same would be appreciated for normal usage, or at least lazy loading because sdk, both v3 and v4 consumes trendemous amount of network data, comparing to google maps (x6-8)

**Comment by datasun** [comment]
I am not sure if the documentation pages are optimized for mobile usage, as development is also not possible from a mobile device. 

Anyway, regarding data usage - google maps offers just a small sub-set of what the HERE SDK can offer, so some difference is expected. However, the 4.x HERE SDK should require much less network traffic compared to 3.x, because the map data format is heavily improved and optimized. 

Regarding feature configuration, all features are enabled by default and lazy loading already happens when possible. However, the recommendation is to disable features before usage, so that the experience stays smooth.

**Comment by Azbesciak** [comment]
> I am not sure if the documentation pages are optimized for mobile usage, as development is also not possible from a mobile device.

Ok, but why should I not read it on the phone...?

> Anyway, regarding data usage - google maps offers just a small sub-set of what the HERE SDK can offer, so some difference is expected. However, the 4.x HERE SDK should require much less network traffic compared to 3.x, because the map data format is heavily improved and optimized.

I compared it on the real life example - our app based on v3 (no other network usage, this app is based on msdkui), vs the current WeGo, same route in android emulator - no difference in data usage, it was about 80MB for 80km route https://www.google.pl/maps/dir/Pozna%C5%84/Leszno/@52.1241866,16.4519223,10z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x470444d2ece10ab7:0xa4ea31980334bfd1!2m2!1d16.9251681!2d52.406374!1m5!1m1!1s0x47059826914dc4d3:0x1b48d36e91c7a321!2m2!1d16.5937545!2d51.8419861!3e0, about 20mb was needed just for the first load without any screen interaction.

> Regarding feature configuration, all features are enabled by default and lazy loading already happens when possible. However, the recommendation is to disable features once before app installation, so that the experience stays smooth.

I did not go so deep into v4 internals/spec, just saying what I see on the very shallow doc/api/example app.

> If you seek for a small network data footprint, consider to use the Lite Edition. It uses a different map format and requires much less data - but also the offering is more limited compared to the other editions.

Unfortunately, it is impossible - we need truck navigation, this is the main feature of the app, and its main purpose - the truck driver navigation. In this topic data usage matters a lot, because foreign country data transfer is limited, also in most of the EU countries, data transfer is not consistent/low quality (3G in Germany even on the highway, as I noticed LTE is also not so common, but I do not live in Germany). BTW our customer tested our app and it consumed 2GB during 2 weeks in Germany before I disabled the SDK network connection during navigation.

I suppose you have different goals, but it is a real-life example and issue.

**Comment by datasun** [comment]
For your use case, you should download all regions that you need onto the device (in advance). We fully support **offline maps**. Then you will download much less data, and you can still use e.g. a `TrafficEngine` on top to get the latest traffic news or show vehicle restrictions. And once we expose the radio silence switch you will download 0 KB of data. Even now, you can use the `OfflineSearchEngine` and `OfflineRoutingEngine` to search and create routes without an internet connection, you can even switch the device to flight mode and still do full tbt navigation.

Alternatively, you can also increase the size of the map cache and change the path to an internal SD card (on Android). Then for subsequent trips less data should be required. 

Hope this helps.

**Comment by Azbesciak** [comment]
> For your use case, you should download all regions that you need onto the device (in advance)

You know that if I would tell my client to download 20GB of maps, on each of his devices, he would (not sure if my PM already didn't) hear that 'for google maps, I do not have to'? Really, people download google maps offline maps only when they do not have internet access, not because otherwise, they would go bankrupt.

Not to mention that maps are versioned and need to be updated.

**Comment by datasun** [comment]
Thanks for the feedback! Just as a hint: Why would you need to download 20GB + x if you don't need this data all the time? Instead, you can just download the countries you need for a trip ... Google maps does not offer a similar feature at all, as you get complete data you can search, route & navigate offline.

At the moment, there are no plans to equip the _Lite Edition_ with TBT guidance.

**Comment by Azbesciak** [comment]
Yeah, as I remember google allow to download any number of bounding boxes. Not sure but in v3 there was something similar, what does not change that I would not like to download anything a priori... :/

About lite - I thought about it a year ago when I started to Explorer the sdk subject, and there was a  significant difference in both visualization and functionality, so from this perspective this is also not a solution, but thank you for giving any suggestion.

However, I still would expect just an optimization on the data usage side, but probably this is not a valid place for it, so let me stop at this Point. 

Thank you both for the conversation and your work :)
