### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Azbesciak** [heremaps/here-sdk-ref-app-flutter#47]
...Because it looks so. I suppose that the example app (msdkui) was supported till the end, whereas the last commit for this one is from January. 
Maybe you would just open source WeGo, or some components from it as a library, in the same way as the msdkui was published, or via flutter pub?

**Comment by stefan-troyke** [comment]
Hi,

this project is not abandoned and updates are planned, but currently not executed. I will follow up with the project management about the request for UI components.
