### ISSUE TITLE
Here Map is not in the backward of all stack widget.

### ISSUE THREAD

**Issue by izzabellerina** [heremaps/here-sdk-ref-app-flutter#48]
Hello everyone, so I face the problem is that the here map is on the front of all stack widgets and it covers all of the stack widgets even bottomNavigationBar and appbar or else. I have tried to use the here map in another project and it worked before. but now it does not work for any project anyway.
What should I do?

This is my flutter doctor.
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/pnall02/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM A105G (mobile) • R58M78MSNQJ • android-arm    • Android 9 (API 28)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by MaKra** [comment]
In case you are using flutter3, there are major bugs in Flutter 3 affecting platform views (for many 3rd party plugins): 
  https://github.com/flutter/flutter/issues/103630 
this will probably get fixed with Flutter 3.1 as I can read on the flutter thread.
As a workaround downgrading to Flutter 2.10 would be the only way around.

**Comment by izzabellerina** [comment]
> In case you are using flutter3, there are major bugs in Flutter 3 affecting platform views (for many 3rd party plugins): [flutter/flutter#103630](https://github.com/flutter/flutter/issues/103630) this will probably get fixed with Flutter 3.1 as I can read on the flutter thread. As a workaround downgrading to Flutter 2.10 would be the only way around.

ok , Thank you

**Comment by stuartmorgan** [comment]
Does this reproduce on Flutter `master`? There's a complicated set of changes that affect different plugins differently, and I don't have access to the plugin so I can't tell which codepath they are on, and if the changes that have already been made addressed this plugin's issue or not.

@ppiatkowski-here Could you provide any information about the platform view mode this plugin uses? Specifically:
- Prior to Flutter 3.0, was it using Virtual Display, or Hybrid Composition?
- Is the underlying android view the plugin vends a `SurfaceView`? (If not, is it a `TextureView`? Other?)

**Comment by stuartmorgan** [comment]
Thanks for the information; it sounds like this was indeed fixed by the change to keep `SurfaceView` plugins on the Virtual Display codepath.

**Comment by stefan-troyke** [comment]
We started testing the latest Flutter version and hope it fixes the mentioned issue. We plan the Flutter 3.3.x support for version 1.5.0.

**Comment by stefan-troyke** [comment]
Hi, we integrated the Flutter version 3.3.2 and if you switch to the usage of hybrid composition in combination to render to an texture view you can workaround the issues for Android 12.

The corresponding Flutter ticket is https://github.com/flutter/flutter/issues/89558. See especially comment https://github.com/flutter/flutter/issues/89558#issuecomment-1275720847.
