### ISSUE TITLE
Map pin moves while panning

### ISSUE THREAD

**Issue by AndyDavidJoyce** [heremaps/here-sdk-ref-app-flutter#63]
I have been working through the reference app to get an understanding of how Here Maps works. One thing I have noticed is that while panning, the map pins seem to move while the marker does not move at all. Is there any way to avoid this? 

https://user-images.githubusercontent.com/7745380/197228546-f9d21fe7-b3bc-48b8-a656-d9fc0f5a31e1.mp4

SDK Version: 4.12.3

**Comment by stefan-troyke** [comment]
Hi,

a view pin is allways attached to a map but not part of the map. That's the reason why you see these delays in the movement while panning the map. A workaround would be to use inline data SVGs instead as we did for the POIs along the route. Please have a look into this code.

**Comment by AndyDavidJoyce** [comment]
@stefan-troyke, thanks for the reply. To clarify, do you mean using SVGs and markers instead of using pins?

**Comment by stefan-troyke** [comment]
Yes, you can use a map marker and load a SVG data as string, see:

- https://developer.here.com/documentation/flutter-sdk-navigate/api_reference/mapview/MapMarker/MapMarker.withAnchor.html
- https://developer.here.com/documentation/flutter-sdk-navigate/api_reference/mapview/MapImage/MapImage.withImageDataImageFormatWidthAndHeight.html with ImageFormat.svg
- https://github.com/heremaps/here-sdk-ref-app-flutter/blob/master/lib/routing/poi_svg_helper.dart
